# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 585b283e5cb7b02cda8ebe35ec9fdb4258fb251727c06722fade8e7c95271648bbc5ae17b296e1420280e95e6590de7f202e8ea13d93148e8f155f8806634e5b
  facebook_app_id: 1628072800764751
  facebook_app_secret: dee60b2e9b9237feb5592067b0fd0c45
  twitter_app_id: DfDPUDGJLDaIebrly5wLiZCjk
  twitter_app_secret: dFJmDr0AkK7R3My2RJhRjF00321741Wfu3gPLFVl2ZzXYrz1gs
test:
  secret_key_base: b76e13f686498528a6e373373e5ca4785d95d3f953b6b61011d1a03cd9a07b7a4fc96d48f7829754a5b6b605b88af86d6a3492113ae6bd9f8c8797da833435e7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  facebook_app_id: <%= ENV["FACEBOOK_APP_ID"] %>
  facebook_app_secret: <%= ENV["FACEBOOK_APP_SECRET"] %>

